/**
 * Generate a custom page informations
 * @param  {Object} defaultInfos  Default informations generated by Gatsby
 * @return {Object}               Customized page object
 */
const generatePagesInfos = (
  { path: pathPath, ...defaultInfos } = {},
  locales = [],
) =>
  locales.map(language => ({
    ...defaultInfos,
    context: {
      language,
      namespace: 'default',
    },
    path: `/${language}${pathPath}`,
  }));

exports.onCreatePage = async (
  { page, actions: { createPage } },
  // plugin options
  { locales },
) => {
  const i18nPages = generatePagesInfos(page, locales);

  // Create custom i18n pages
  i18nPages.map(i18nPage => createPage(i18nPage));
};
