/**
 * Generate a custom page informations
 * @param  {Object} defaultInfos  Default informations generated by Gatsby
 * @return {Object}               Customized page object
 */
exports.generatePagesInfos = (
  { path: pathPath, ...defaultInfos } = {},
  locales = [],
) =>
  locales.map(language => ({
    ...defaultInfos,
    context: {
      language,
      namespace: 'default',
    },
    path: `/${language}${pathPath}`,
  }));
